# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from airport_load_server.models.base_model_ import Model
from airport_load_server import util


class BriefAirportLoadInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, airport_code: str=None, pax_load: int=None, latitude: float=None, longititude: float=None):
        """BriefAirportLoadInfo - a model defined in OpenAPI

        :param airport_code: The airport_code of this BriefAirportLoadInfo.
        :param pax_load: The pax_load of this BriefAirportLoadInfo.
        :param latitude: The latitude of this BriefAirportLoadInfo.
        :param longititude: The longititude of this BriefAirportLoadInfo.
        """
        self.openapi_types = {
            'airport_code': str,
            'pax_load': int,
            'latitude': float,
            'longititude': float
        }

        self.attribute_map = {
            'airport_code': 'airportCode',
            'pax_load': 'paxLoad',
            'latitude': 'latitude',
            'longititude': 'longititude'
        }

        self._airport_code = airport_code
        self._pax_load = pax_load
        self._latitude = latitude
        self._longititude = longititude

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BriefAirportLoadInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BriefAirportLoadInfo of this BriefAirportLoadInfo.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def airport_code(self):
        """Gets the airport_code of this BriefAirportLoadInfo.


        :return: The airport_code of this BriefAirportLoadInfo.
        :rtype: str
        """
        return self._airport_code

    @airport_code.setter
    def airport_code(self, airport_code):
        """Sets the airport_code of this BriefAirportLoadInfo.


        :param airport_code: The airport_code of this BriefAirportLoadInfo.
        :type airport_code: str
        """
        if airport_code is None:
            raise ValueError("Invalid value for `airport_code`, must not be `None`")

        self._airport_code = airport_code

    @property
    def pax_load(self):
        """Gets the pax_load of this BriefAirportLoadInfo.


        :return: The pax_load of this BriefAirportLoadInfo.
        :rtype: int
        """
        return self._pax_load

    @pax_load.setter
    def pax_load(self, pax_load):
        """Sets the pax_load of this BriefAirportLoadInfo.


        :param pax_load: The pax_load of this BriefAirportLoadInfo.
        :type pax_load: int
        """

        self._pax_load = pax_load

    @property
    def latitude(self):
        """Gets the latitude of this BriefAirportLoadInfo.


        :return: The latitude of this BriefAirportLoadInfo.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this BriefAirportLoadInfo.


        :param latitude: The latitude of this BriefAirportLoadInfo.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longititude(self):
        """Gets the longititude of this BriefAirportLoadInfo.


        :return: The longititude of this BriefAirportLoadInfo.
        :rtype: float
        """
        return self._longititude

    @longititude.setter
    def longititude(self, longititude):
        """Sets the longititude of this BriefAirportLoadInfo.


        :param longititude: The longititude of this BriefAirportLoadInfo.
        :type longititude: float
        """

        self._longititude = longititude
