# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from airport_load_server.models.base_model_ import Model
from airport_load_server.models.flight_airport_load_info import FlightAirportLoadInfo
from airport_load_server import util


class DetailedAirportLoadInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, airport_code: str=None, pax_y_load: int=None, pax_c_load: int=None, children_y_load: int=None, children_c_load: int=None, infants_y_load: int=None, infants_c_load: int=None, latitude: float=None, longititude: float=None, flights: List[FlightAirportLoadInfo]=None):
        """DetailedAirportLoadInfo - a model defined in OpenAPI

        :param airport_code: The airport_code of this DetailedAirportLoadInfo.
        :param pax_y_load: The pax_y_load of this DetailedAirportLoadInfo.
        :param pax_c_load: The pax_c_load of this DetailedAirportLoadInfo.
        :param children_y_load: The children_y_load of this DetailedAirportLoadInfo.
        :param children_c_load: The children_c_load of this DetailedAirportLoadInfo.
        :param infants_y_load: The infants_y_load of this DetailedAirportLoadInfo.
        :param infants_c_load: The infants_c_load of this DetailedAirportLoadInfo.
        :param latitude: The latitude of this DetailedAirportLoadInfo.
        :param longititude: The longititude of this DetailedAirportLoadInfo.
        :param flights: The flights of this DetailedAirportLoadInfo.
        """
        self.openapi_types = {
            'airport_code': str,
            'pax_y_load': int,
            'pax_c_load': int,
            'children_y_load': int,
            'children_c_load': int,
            'infants_y_load': int,
            'infants_c_load': int,
            'latitude': float,
            'longititude': float,
            'flights': List[FlightAirportLoadInfo]
        }

        self.attribute_map = {
            'airport_code': 'airportCode',
            'pax_y_load': 'paxYLoad',
            'pax_c_load': 'paxCLoad',
            'children_y_load': 'childrenYLoad',
            'children_c_load': 'childrenCLoad',
            'infants_y_load': 'infantsYLoad',
            'infants_c_load': 'infantsCLoad',
            'latitude': 'latitude',
            'longititude': 'longititude',
            'flights': 'flights'
        }

        self._airport_code = airport_code
        self._pax_y_load = pax_y_load
        self._pax_c_load = pax_c_load
        self._children_y_load = children_y_load
        self._children_c_load = children_c_load
        self._infants_y_load = infants_y_load
        self._infants_c_load = infants_c_load
        self._latitude = latitude
        self._longititude = longititude
        self._flights = flights

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DetailedAirportLoadInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DetailedAirportLoadInfo of this DetailedAirportLoadInfo.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def airport_code(self):
        """Gets the airport_code of this DetailedAirportLoadInfo.


        :return: The airport_code of this DetailedAirportLoadInfo.
        :rtype: str
        """
        return self._airport_code

    @airport_code.setter
    def airport_code(self, airport_code):
        """Sets the airport_code of this DetailedAirportLoadInfo.


        :param airport_code: The airport_code of this DetailedAirportLoadInfo.
        :type airport_code: str
        """
        if airport_code is None:
            raise ValueError("Invalid value for `airport_code`, must not be `None`")

        self._airport_code = airport_code

    @property
    def pax_y_load(self):
        """Gets the pax_y_load of this DetailedAirportLoadInfo.


        :return: The pax_y_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._pax_y_load

    @pax_y_load.setter
    def pax_y_load(self, pax_y_load):
        """Sets the pax_y_load of this DetailedAirportLoadInfo.


        :param pax_y_load: The pax_y_load of this DetailedAirportLoadInfo.
        :type pax_y_load: int
        """

        self._pax_y_load = pax_y_load

    @property
    def pax_c_load(self):
        """Gets the pax_c_load of this DetailedAirportLoadInfo.


        :return: The pax_c_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._pax_c_load

    @pax_c_load.setter
    def pax_c_load(self, pax_c_load):
        """Sets the pax_c_load of this DetailedAirportLoadInfo.


        :param pax_c_load: The pax_c_load of this DetailedAirportLoadInfo.
        :type pax_c_load: int
        """

        self._pax_c_load = pax_c_load

    @property
    def children_y_load(self):
        """Gets the children_y_load of this DetailedAirportLoadInfo.


        :return: The children_y_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._children_y_load

    @children_y_load.setter
    def children_y_load(self, children_y_load):
        """Sets the children_y_load of this DetailedAirportLoadInfo.


        :param children_y_load: The children_y_load of this DetailedAirportLoadInfo.
        :type children_y_load: int
        """

        self._children_y_load = children_y_load

    @property
    def children_c_load(self):
        """Gets the children_c_load of this DetailedAirportLoadInfo.


        :return: The children_c_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._children_c_load

    @children_c_load.setter
    def children_c_load(self, children_c_load):
        """Sets the children_c_load of this DetailedAirportLoadInfo.


        :param children_c_load: The children_c_load of this DetailedAirportLoadInfo.
        :type children_c_load: int
        """

        self._children_c_load = children_c_load

    @property
    def infants_y_load(self):
        """Gets the infants_y_load of this DetailedAirportLoadInfo.


        :return: The infants_y_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._infants_y_load

    @infants_y_load.setter
    def infants_y_load(self, infants_y_load):
        """Sets the infants_y_load of this DetailedAirportLoadInfo.


        :param infants_y_load: The infants_y_load of this DetailedAirportLoadInfo.
        :type infants_y_load: int
        """

        self._infants_y_load = infants_y_load

    @property
    def infants_c_load(self):
        """Gets the infants_c_load of this DetailedAirportLoadInfo.


        :return: The infants_c_load of this DetailedAirportLoadInfo.
        :rtype: int
        """
        return self._infants_c_load

    @infants_c_load.setter
    def infants_c_load(self, infants_c_load):
        """Sets the infants_c_load of this DetailedAirportLoadInfo.


        :param infants_c_load: The infants_c_load of this DetailedAirportLoadInfo.
        :type infants_c_load: int
        """

        self._infants_c_load = infants_c_load

    @property
    def latitude(self):
        """Gets the latitude of this DetailedAirportLoadInfo.


        :return: The latitude of this DetailedAirportLoadInfo.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this DetailedAirportLoadInfo.


        :param latitude: The latitude of this DetailedAirportLoadInfo.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longititude(self):
        """Gets the longititude of this DetailedAirportLoadInfo.


        :return: The longititude of this DetailedAirportLoadInfo.
        :rtype: float
        """
        return self._longititude

    @longititude.setter
    def longititude(self, longititude):
        """Sets the longititude of this DetailedAirportLoadInfo.


        :param longititude: The longititude of this DetailedAirportLoadInfo.
        :type longititude: float
        """

        self._longititude = longititude

    @property
    def flights(self):
        """Gets the flights of this DetailedAirportLoadInfo.


        :return: The flights of this DetailedAirportLoadInfo.
        :rtype: List[FlightAirportLoadInfo]
        """
        return self._flights

    @flights.setter
    def flights(self, flights):
        """Sets the flights of this DetailedAirportLoadInfo.


        :param flights: The flights of this DetailedAirportLoadInfo.
        :type flights: List[FlightAirportLoadInfo]
        """

        self._flights = flights
