# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import auth_aiohttp_client
from auth_aiohttp_client.api.admin_api import AdminApi  # noqa: E501
from auth_aiohttp_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = auth_aiohttp_client.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_add_group(self):
        """Test case for admin_add_group

        add new group  # noqa: E501
        """
        pass

    def test_admin_add_user(self):
        """Test case for admin_add_user

        add new user  # noqa: E501
        """
        pass

    def test_admin_get_group(self):
        """Test case for admin_get_group

        Get group  # noqa: E501
        """
        pass

    def test_admin_get_user_info(self):
        """Test case for admin_get_user_info

        Get user info  # noqa: E501
        """
        pass

    def test_admin_group_put(self):
        """Test case for admin_group_put

        Edit group  # noqa: E501
        """
        pass

    def test_admin_list_groups(self):
        """Test case for admin_list_groups

        list all groups  # noqa: E501
        """
        pass

    def test_admin_list_users(self):
        """Test case for admin_list_users

        list all users  # noqa: E501
        """
        pass

    def test_admin_remove_group(self):
        """Test case for admin_remove_group

        Remove group from the system  # noqa: E501
        """
        pass

    def test_admin_remove_user(self):
        """Test case for admin_remove_user

        Remove user from the system  # noqa: E501
        """
        pass

    def test_admin_user_put(self):
        """Test case for admin_user_put

        Edit user  # noqa: E501
        """
        pass

    def test_generate_refresh_token(self):
        """Test case for generate_refresh_token

        generate refresh token with arbitrary lifetime e.g. for services  # noqa: E501
        """
        pass

    def test_get_token_info(self):
        """Test case for get_token_info

        list all refresh tokens  # noqa: E501
        """
        pass

    def test_list_refresh_tokens(self):
        """Test case for list_refresh_tokens

        list all refresh tokens  # noqa: E501
        """
        pass

    def test_revoke_refresh_token(self):
        """Test case for revoke_refresh_token

        generate refresh token with arbitrary lifetime e.g. for services  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
