# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import auth_aiohttp_client
from auth_aiohttp_client.api.health_api import HealthApi  # noqa: E501
from auth_aiohttp_client.rest import ApiException


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = auth_aiohttp_client.api.health_api.HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_liveness_get(self):
        """Test case for health_liveness_get

        liveness probe  # noqa: E501
        """
        pass

    def test_health_readiness_get(self):
        """Test case for health_readiness_get

        readiness probe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
