# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import auth_aiohttp_client
from auth_aiohttp_client.models.tokens import Tokens  # noqa: E501
from auth_aiohttp_client.rest import ApiException

class TestTokens(unittest.TestCase):
    """Tokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Tokens
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = auth_aiohttp_client.models.tokens.Tokens()  # noqa: E501
        if include_optional :
            return Tokens(
                refresh_token = auth_aiohttp_client.models.token_response.TokenResponse(
                    token = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                access_token = auth_aiohttp_client.models.token_response.TokenResponse(
                    token = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else :
            return Tokens(
        )

    def testTokens(self):
        """Test Tokens"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
