# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import auth_aiohttp_client
from auth_aiohttp_client.api.auth_api import AuthApi  # noqa: E501
from auth_aiohttp_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = auth_aiohttp_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_google(self):
        """Test case for auth_google

        Authenticate on Google  # noqa: E501
        """
        pass

    def test_get_public_key(self):
        """Test case for get_public_key

        get public key to decrypt access tokens  # noqa: E501
        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        get user information  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Authenticate on OpenID  # noqa: E501
        """
        pass

    def test_open_google_auth(self):
        """Test case for open_google_auth

        Redirect to Google Authentication  # noqa: E501
        """
        pass

    def test_refresh(self):
        """Test case for refresh

        generate access token from refresh token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
