"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_python_client
from auth_python_client.model.user_in_group import UserInGroup
globals()['UserInGroup'] = UserInGroup
from auth_python_client.model.group_full import GroupFull


class TestGroupFull(unittest.TestCase):
    """GroupFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupFull(self):
        """Test GroupFull"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupFull()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
