"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_python_client
from auth_python_client.model.group_info import GroupInfo
globals()['GroupInfo'] = GroupInfo
from auth_python_client.model.admin_refresh_token_info_post import AdminRefreshTokenInfoPost


class TestAdminRefreshTokenInfoPost(unittest.TestCase):
    """AdminRefreshTokenInfoPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminRefreshTokenInfoPost(self):
        """Test AdminRefreshTokenInfoPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdminRefreshTokenInfoPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
