"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_python_client
from auth_python_client.model.token_response import TokenResponse
globals()['TokenResponse'] = TokenResponse
from auth_python_client.model.tokens import Tokens


class TestTokens(unittest.TestCase):
    """Tokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokens(self):
        """Test Tokens"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tokens()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
