"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth_python_client
from auth_python_client.model.group_full import GroupFull
globals()['GroupFull'] = GroupFull
from auth_python_client.model.group_list import GroupList


class TestGroupList(unittest.TestCase):
    """GroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupList(self):
        """Test GroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
