# Default values for application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#
image:
  imagePullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: DB_SCHEMA
    value: "auth"
  - name: "PORT"
    value: "8080"

imageCredentials:
  secretName: mipt-pull-secret

envFrom:
  - secretRef:
      name: auth-db-secret
  - secretRef:
      name: sso-secret
  - secretRef:
      name: flask-secret
  - secretRef:
      name: auth-secret
containers:
  containerPort: 8080
  readinessProbePath: /api/auth/v2/health/readiness
  livenessProbePath: /api/auth/v2/health/liveness

service:
  type: ClusterIP
  name: auth
  port: 8080

ingress:
  enabled: true
  tls: true
  hosts:
    - paths:
        - path: /api/auth/v1
          serviceName: auth
  annotations:
    certmanager.k8s.io/issuer: vault-mipt


#   args: []
#   volumeMounts: []
#   restartPolicy: Never
#   volumes: []
#   schedule:  "*/1 * * * *"
#   successfulJobsHistoryLimit: 1


resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
