# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from auth_aiohttp_client.configuration import Configuration


class AdminRefreshTokenList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'refresh_token_info': 'list[AdminRefreshTokenInfo]'
    }

    attribute_map = {
        'refresh_token_info': 'refreshTokenInfo'
    }

    def __init__(self, refresh_token_info=None, local_vars_configuration=None):  # noqa: E501
        """AdminRefreshTokenList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._refresh_token_info = None
        self.discriminator = None

        if refresh_token_info is not None:
            self.refresh_token_info = refresh_token_info

    @property
    def refresh_token_info(self):
        """Gets the refresh_token_info of this AdminRefreshTokenList.  # noqa: E501


        :return: The refresh_token_info of this AdminRefreshTokenList.  # noqa: E501
        :rtype: list[AdminRefreshTokenInfo]
        """
        return self._refresh_token_info

    @refresh_token_info.setter
    def refresh_token_info(self, refresh_token_info):
        """Sets the refresh_token_info of this AdminRefreshTokenList.


        :param refresh_token_info: The refresh_token_info of this AdminRefreshTokenList.  # noqa: E501
        :type refresh_token_info: list[AdminRefreshTokenInfo]
        """

        self._refresh_token_info = refresh_token_info

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminRefreshTokenList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdminRefreshTokenList):
            return True

        return self.to_dict() != other.to_dict()
