# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from auth_aiohttp_client.configuration import Configuration


class GroupInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'group_id': 'str',
        'description': 'str',
        'mode': 'str'
    }

    attribute_map = {
        'group_id': 'groupId',
        'description': 'description',
        'mode': 'mode'
    }

    def __init__(self, group_id=None, description=None, mode=None, local_vars_configuration=None):  # noqa: E501
        """GroupInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._group_id = None
        self._description = None
        self._mode = None
        self.discriminator = None

        if group_id is not None:
            self.group_id = group_id
        if description is not None:
            self.description = description
        if mode is not None:
            self.mode = mode

    @property
    def group_id(self):
        """Gets the group_id of this GroupInfo.  # noqa: E501


        :return: The group_id of this GroupInfo.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this GroupInfo.


        :param group_id: The group_id of this GroupInfo.  # noqa: E501
        :type group_id: str
        """

        self._group_id = group_id

    @property
    def description(self):
        """Gets the description of this GroupInfo.  # noqa: E501


        :return: The description of this GroupInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GroupInfo.


        :param description: The description of this GroupInfo.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def mode(self):
        """Gets the mode of this GroupInfo.  # noqa: E501


        :return: The mode of this GroupInfo.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this GroupInfo.


        :param mode: The mode of this GroupInfo.  # noqa: E501
        :type mode: str
        """
        allowed_values = ["READ", "WRITE", "ADMIN"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and mode not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupInfo):
            return True

        return self.to_dict() != other.to_dict()
