# coding: utf-8

"""
    Auth server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from auth_aiohttp_client.configuration import Configuration


class Tokens(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'refresh_token': 'TokenResponse',
        'access_token': 'TokenResponse'
    }

    attribute_map = {
        'refresh_token': 'refreshToken',
        'access_token': 'accessToken'
    }

    def __init__(self, refresh_token=None, access_token=None, local_vars_configuration=None):  # noqa: E501
        """Tokens - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._refresh_token = None
        self._access_token = None
        self.discriminator = None

        if refresh_token is not None:
            self.refresh_token = refresh_token
        if access_token is not None:
            self.access_token = access_token

    @property
    def refresh_token(self):
        """Gets the refresh_token of this Tokens.  # noqa: E501


        :return: The refresh_token of this Tokens.  # noqa: E501
        :rtype: TokenResponse
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this Tokens.


        :param refresh_token: The refresh_token of this Tokens.  # noqa: E501
        :type refresh_token: TokenResponse
        """

        self._refresh_token = refresh_token

    @property
    def access_token(self):
        """Gets the access_token of this Tokens.  # noqa: E501


        :return: The access_token of this Tokens.  # noqa: E501
        :rtype: TokenResponse
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this Tokens.


        :param access_token: The access_token of this Tokens.  # noqa: E501
        :type access_token: TokenResponse
        """

        self._access_token = access_token

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tokens):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Tokens):
            return True

        return self.to_dict() != other.to_dict()
