# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from dsm_auth_server.models.base_model_ import Model
from dsm_auth_server import util


class GroupPost(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_id: str=None, description: str=None):
        """GroupPost - a model defined in OpenAPI

        :param group_id: The group_id of this GroupPost.
        :param description: The description of this GroupPost.
        """
        self.openapi_types = {
            'group_id': str,
            'description': str
        }

        self.attribute_map = {
            'group_id': 'groupId',
            'description': 'description'
        }

        self._group_id = group_id
        self._description = description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GroupPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GroupPost of this GroupPost.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_id(self):
        """Gets the group_id of this GroupPost.


        :return: The group_id of this GroupPost.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this GroupPost.


        :param group_id: The group_id of this GroupPost.
        :type group_id: str
        """

        self._group_id = group_id

    @property
    def description(self):
        """Gets the description of this GroupPost.


        :return: The description of this GroupPost.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GroupPost.


        :param description: The description of this GroupPost.
        :type description: str
        """

        self._description = description
