# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from dsm_auth_server.models.base_model_ import Model
from dsm_auth_server.models.group_full import GroupFull
from dsm_auth_server import util


class GroupList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, groups: List[GroupFull]=None):
        """GroupList - a model defined in OpenAPI

        :param groups: The groups of this GroupList.
        """
        self.openapi_types = {
            'groups': List[GroupFull]
        }

        self.attribute_map = {
            'groups': 'groups'
        }

        self._groups = groups

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GroupList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GroupList of this GroupList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def groups(self):
        """Gets the groups of this GroupList.


        :return: The groups of this GroupList.
        :rtype: List[GroupFull]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this GroupList.


        :param groups: The groups of this GroupList.
        :type groups: List[GroupFull]
        """

        self._groups = groups
