# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from dsm_auth_server.models.base_model_ import Model
from dsm_auth_server import util


class PublicKey(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, public_key: str=None):
        """PublicKey - a model defined in OpenAPI

        :param public_key: The public_key of this PublicKey.
        """
        self.openapi_types = {
            'public_key': str
        }

        self.attribute_map = {
            'public_key': 'publicKey'
        }

        self._public_key = public_key

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PublicKey':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PublicKey of this PublicKey.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def public_key(self):
        """Gets the public_key of this PublicKey.


        :return: The public_key of this PublicKey.
        :rtype: str
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this PublicKey.


        :param public_key: The public_key of this PublicKey.
        :type public_key: str
        """

        self._public_key = public_key
