# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from dsm_auth_server.models.base_model_ import Model
from dsm_auth_server.models.token_response import TokenResponse
from dsm_auth_server import util


class Tokens(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, refresh_token: TokenResponse=None, access_token: TokenResponse=None):
        """Tokens - a model defined in OpenAPI

        :param refresh_token: The refresh_token of this Tokens.
        :param access_token: The access_token of this Tokens.
        """
        self.openapi_types = {
            'refresh_token': TokenResponse,
            'access_token': TokenResponse
        }

        self.attribute_map = {
            'refresh_token': 'refreshToken',
            'access_token': 'accessToken'
        }

        self._refresh_token = refresh_token
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Tokens':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Tokens of this Tokens.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refresh_token(self):
        """Gets the refresh_token of this Tokens.


        :return: The refresh_token of this Tokens.
        :rtype: TokenResponse
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this Tokens.


        :param refresh_token: The refresh_token of this Tokens.
        :type refresh_token: TokenResponse
        """

        self._refresh_token = refresh_token

    @property
    def access_token(self):
        """Gets the access_token of this Tokens.


        :return: The access_token of this Tokens.
        :rtype: TokenResponse
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this Tokens.


        :param access_token: The access_token of this Tokens.
        :type access_token: TokenResponse
        """

        self._access_token = access_token
