# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from dsm_auth_server.models.base_model_ import Model
from dsm_auth_server import util


class TokenResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token: str=None, expires_at: datetime=None):
        """TokenResponse - a model defined in OpenAPI

        :param token: The token of this TokenResponse.
        :param expires_at: The expires_at of this TokenResponse.
        """
        self.openapi_types = {
            'token': str,
            'expires_at': datetime
        }

        self.attribute_map = {
            'token': 'token',
            'expires_at': 'expiresAt'
        }

        self._token = token
        self._expires_at = expires_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TokenResponse of this TokenResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this TokenResponse.


        :return: The token of this TokenResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenResponse.


        :param token: The token of this TokenResponse.
        :type token: str
        """

        self._token = token

    @property
    def expires_at(self):
        """Gets the expires_at of this TokenResponse.


        :return: The expires_at of this TokenResponse.
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this TokenResponse.


        :param expires_at: The expires_at of this TokenResponse.
        :type expires_at: datetime
        """

        self._expires_at = expires_at
