/**
 * Auth server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupInfo } from './groupInfo';


export interface UserInfo { 
    userId?: string;
    globalRole?: UserInfo.GlobalRoleEnum;
    groups?: Array<GroupInfo>;
}
export namespace UserInfo {
    export type GlobalRoleEnum = 'ADMIN' | 'USER';
    export const GlobalRoleEnum = {
        Admin: 'ADMIN' as GlobalRoleEnum,
        User: 'USER' as GlobalRoleEnum
    };
}


